### Numpy: Package for Multidimesional array (Numerical Python transformation using python)

### Vector(1d)

### Matrix(2d or 1d)

In [3]:
import numpy as np

In [ ]:
example_list= [1,2,3,4,5,6]
example_array = np.array(example_list)
example_array

### 2d/3d

In [12]:
twod_array= np.array(([0,9,8,7,6],[5,4,3,2,1]))
threed_array= np.array(([0,9,8,7,6],[5,4,3,2,1],[0,9,3,2,1]))


### Arange(n,k) ->   numbers from n to k-1 with equal difference of 1





In [ ]:
np.arange(2,100)

### Arange(n,k,m) ->   numbers from n to k-1 with equal difference of m


In [ ]:
np.arange(2,100,5)

### Zeros --> results in all zeros

In [ ]:
np.zeros(5)

### Zeros(5,dtype=int) --> results in all zeros as int

In [ ]:
np.zeros(5,dtype=int)

### Ones --> results in all ones

In [ ]:
np.ones(5)

### Ones(5,dtype=int) --> results in all ones and integers

In [ ]:
np.ones(5,dtype=int)

### Ones((5,2),dtype=int) --> results in all ones and integers , 5 rows 2 columns matrix


In [ ]:
np.ones((5,2),dtype=int)

### linspace(a,b,c) -->  from a to < b , into c parts , in float

In [ ]:
np.linspace(1,5,4)

### linspace(a,b,c) -->  from a to < b , into c parts , in int

In [ ]:
np.linspace(1,5,4,dtype=int)

### eye(a,b)  --> Identity Matrix with a rows and b columns  , dtype can be used to int 

In [ ]:
np.eye(2,3)

### np.random.rand(3) --> random value from 0 to 1 , with 3 columns , similary randn for negative values
###  randint(1,3)  --> random integer from 1 to 3 for integers  , randint(1,10,3)  random 3 from 1 to 10

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.randn(2,3)

In [ ]:
np.random.randint(10,100,15)

### array.min() --> for min of array , array.max() --> for max of array , array.argmin() --> index where min is in the array

In [ ]:
example_array.min()

In [ ]:
example_array.argmax()

In [ ]:
example_array.argmin()

In [ ]:
example_array.dtype

In [8]:
array_required = np.array((1,2,3,4,5,6,7,8,9,0))

In [9]:
array_required[1:4]= 0

In [10]:
array_required

array([1, 0, 0, 0, 5, 6, 7, 8, 9, 0])

In [13]:
threed_array

array([[0, 9, 8, 7, 6],
       [5, 4, 3, 2, 1],
       [0, 9, 3, 2, 1]])

In [32]:
threed_array[1:3,1:3]

array([[4, 3],
       [9, 3]])